name: Docker Image

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - 'master'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: "./Dockerfile.lib"
          tags: ghcr.io/${{ github.repository }}:opencv4
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache4
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache4,mode=max