name: Docker Image

on:
  push:
    branches:
      - 'master'
      - 'action'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: "./Dockerfile.lib"
          tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:latest